services:
  accounts:
    image: "adityadange07/accounts:latest"
    container_name: accounts-ms
    ports:
      - "9001:9001"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank
  cards:
    image: "adityadange07/cards:latest"
    container_name: cards-ms
    ports:
      - "9002:9002"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank
  loans:
    image: "adityadange07/loans:latest"
    container_name: loans-ms
    ports:
      - "9003:9003"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank
networks:
  bank:
    driver: "bridge"